import type { Doctor, Report } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImageUrl = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageUrl || '';

export const doctors: Doctor[] = [
  {
    id: 'D001',
    name: 'Dr. Petra Winsburry',
    specialty: 'Routine Check-Ups',
    avatar: "https://picsum.photos/seed/doc1/100/100",
    schedule: 'Mon, Wed, Fri: 9 AM - 5 PM. Short lunch breaks.',
    preferences: 'Prefers back-to-back consultations in the morning to leave afternoons for administrative tasks. Avoids scheduling follow-ups on Fridays.',
    historicalData: 'Tends to run 15 minutes late for afternoon appointments. High patient satisfaction scores.',
    department: 'General Medicine',
    totalPatients: 150,
    todaysAppointments: 10,
    availability: 'Available',
  },
  {
    id: 'D002',
    name: 'Dr. Olivia Martinez',
    specialty: 'Heart Specialist',
    avatar: "https://picsum.photos/seed/doc2/100/100",
    schedule: 'Tue, Thu: 8 AM - 4 PM. Strict on-time appointments.',
    preferences: 'Likes to have 10-minute gaps between patients for note-taking. Prefers complex cases in the early afternoon.',
    historicalData: 'Appointment lengths are very consistent. Rarely cancels appointments.',
    department: 'Cardiology',
    totalPatients: 200,
    todaysAppointments: 0,
    availability: 'Unavailable',
  },
  {
    id: 'D003',
    name: 'Dr. Damian Sanchez',
    specialty: 'Child Health',
    avatar: "https://picsum.photos/seed/doc3/100/100",
    schedule: 'Mon-Fri: 10 AM - 6 PM. Flexible with walk-ins.',
    preferences: 'Does not want more than 3 new patient check-ups per day. Prefers longer slots for infants.',
    historicalData: 'Often extends appointment times for concerned parents, leading to a cascading delay throughout the day.',
    department: 'Pediatrics',
    totalPatients: 180,
    todaysAppointments: 12,
    availability: 'Available',
  },
  {
    id: 'D004',
    name: 'Dr. Chloe Harrington',
    specialty: 'Skin Specialist',
    avatar: "https://picsum.photos/seed/doc4/100/100",
    schedule: 'Mon, Tue, Thu: 9 AM - 5 PM. Surgery on Wednesdays.',
    preferences: 'Prefers post-op appointments on Mondays. No new patient consultations on Thursdays.',
    historicalData: 'Schedule is frequently disrupted by emergency consultations from the ER.',
    department: 'Dermatology',
    totalPatients: 120,
    todaysAppointments: 8,
    availability: 'Available',
  },
    {
    id: 'D005',
    name: 'Dr. Emily Smith',
    specialty: 'Routine Check-Ups',
    avatar: getImageUrl('dr_smith'),
    schedule: 'Mon, Wed, Fri: 9 AM - 5 PM. Short lunch breaks.',
    preferences: 'Prefers back-to-back consultations in the morning to leave afternoons for administrative tasks. Avoids scheduling follow-ups on Fridays.',
    historicalData: 'Tends to run 15 minutes late for afternoon appointments. High patient satisfaction scores.',
    department: 'General Medicine',
    totalPatients: 160,
    todaysAppointments: 0,
    availability: 'Unavailable',
  },
  {
    id: 'D006',
    name: 'Dr. Samuel Thompson',
    specialty: 'Heart Specialist',
    avatar: "https://picsum.photos/seed/doc6/100/100",
    schedule: 'Tue, Thu: 8 AM - 4 PM. Strict on-time appointments.',
    preferences: 'Likes to have 10-minute gaps between patients for note-taking. Prefers complex cases in the early afternoon.',
    historicalData: 'Appointment lengths are very consistent. Rarely cancels appointments.',
    department: 'Cardiology',
    totalPatients: 210,
    todaysAppointments: 14,
    availability: 'Available',
  },
    {
    id: 'D007',
    name: 'Dr. Sarah Johnson',
    specialty: 'Child Health',
    avatar: "https://picsum.photos/seed/doc7/100/100",
    schedule: 'Mon-Fri: 10 AM - 6 PM. Flexible with walk-ins.',
    preferences: 'Does not want more than 3 new patient check-ups per day. Prefers longer slots for infants.',
    historicalData: 'Often extends appointment times for concerned parents, leading to a cascading delay throughout the day.',
    department: 'Pediatrics',
    totalPatients: 170,
    todaysAppointments: 0,
    availability: 'Unavailable',
  },
  {
    id: 'D008',
    name: 'Dr. Luke Harrison',
    specialty: 'Skin Specialist',
    avatar: "https://picsum.photos/seed/doc8/100/100",
    schedule: 'Mon, Tue, Thu: 9 AM - 5 PM. Surgery on Wednesdays.',
    preferences: 'Prefers post-op appointments on Mondays. No new patient consultations on Thursdays.',
    historicalData: 'Schedule is frequently disrupted by emergency consultations from the ER.',
    department: 'Dermatology',
    totalPatients: 130,
    todaysAppointments: 9,
    availability: 'Available',
  },
  {
    id: 'D009',
    name: 'Dr. Andrew Peterson',
    specialty: 'Internal Health',
    avatar: "https://picsum.photos/seed/doc9/100/100",
    schedule: 'Mon-Fri: 10 AM - 6 PM. Flexible with walk-ins.',
    preferences: 'Does not want more than 3 new patient check-ups per day. Prefers longer slots for infants.',
    historicalData: 'Often extends appointment times for concerned parents, leading to a cascading delay throughout the day.',
    department: 'Internal Medicine',
    totalPatients: 190,
    todaysAppointments: 0,
    availability: 'Unavailable',
  },
  {
    id: 'D010',
    name: 'Dr. William Carter',
    specialty: 'Child Health',
    avatar: "https://picsum.photos/seed/doc10/100/100",
    schedule: 'Mon-Fri: 10 AM - 6 PM. Flexible with walk-ins.',
    preferences: 'Does not want more than 3 new patient check-ups per day. Prefers longer slots for infants.',
    historicalData: 'Often extends appointment times for concerned parents, leading to a cascading delay throughout the day.',
    department: 'Pediatrics',
    totalPatients: 175,
    todaysAppointments: 12,
    availability: 'Available',
  },
  {
    id: 'D011',
    name: 'Dr. Mark Wilson',
    specialty: 'Bone Specialist',
    avatar: "https://picsum.photos/seed/doc11/100/100",
    schedule: 'Mon-Fri: 10 AM - 6 PM. Flexible with walk-ins.',
    preferences: 'Does not want more than 3 new patient check-ups per day. Prefers longer slots for infants.',
    historicalData: 'Often extends appointment times for concerned parents, leading to a cascading delay throughout the day.',
    department: 'Orthopedics',
    totalPatients: 140,
    todaysAppointments: 0,
    availability: 'Unavailable',
  },
  {
    id: 'D012',
    name: 'Dr. Thomas Brown',
    specialty: 'Brain Specialist',
    avatar: "https://picsum.photos/seed/doc12/100/100",
    schedule: 'Mon-Fri: 10 AM - 6 PM. Flexible with walk-ins.',
    preferences: 'Does not want more than 3 new patient check-ups per day. Prefers longer slots for infants.',
    historicalData: 'Often extends appointment times for concerned parents, leading to a cascading delay throughout the day.',
    department: 'Neurology',
    totalPatients: 155,
    todaysAppointments: 11,
    availability: 'Available',
  },
];

export const reports: Report[] = [
    { id: 'room-101', name: 'Room 101', statuses: ['Clean', 'Occupied', 'Needs Cleaning'], type: 'room' },
    { id: 'room-102', name: 'Room 102', statuses: ['Occupied', 'Needs Cleaning', 'Clean'], type: 'room' },
    { id: 'mri-1', name: 'MRI Scanner 1', statuses: ['Available', 'In Use', 'Maintenance'], type: 'equipment' },
    { id: 'xray-2', name: 'X-Ray Machine 2', statuses: ['In Use', 'Available', 'Maintenance'], type: 'equipment' },
    { id: 'room-205', name: 'Room 205', statuses: ['Needs Cleaning', 'Clean', 'Occupied'], type: 'room' },
    { id: 'ultrasound-1', name: 'Ultrasound 1', statuses: ['Maintenance', 'Available', 'In Use'], type: 'equipment' },
];

export const user = {
    name: 'Alfredo Westervelt',
    email: 'alfredo.westervelt@wellnest.com',
    avatar: "https://picsum.photos/seed/user/100/100",
};
